### ISSUE TITLE
LA Times, Washington Post not working

### ISSUE THREAD

**Issue by KCeditor** [iamadamdev/bypass-paywalls-chrome#113]

**Comment by sokolq55** [comment]
Same issue - updated to latest version. NYT and WashPo do not work. Seems like these websites change their paywall algos quite frequently.

**Comment by prech** [comment]
> Same issue - updated to latest version. NYT and WashPo do not work. Seems like these websites change their paywall algos quite frequently.

Unfortunately, seeing this, also. v1.4.0

[Washington Post](https://i.imgur.com/h2u5WZy.jpg)

**Comment by jlitz** [comment]
Try Firefox WP NYT work ok there

**Comment by prech** [comment]
> Funny LAT WP NYT work ok on FF WP no go on Chrome but others works

Mind sharing how to install in Firefox? I get an error in "about:debugging":
[Firefox error](https://i.imgur.com/XqDnIWP.jpg)

Just out of curiosity, as I primarily use Chrome :)

**Comment by jlitz** [comment]
download  ff ext  https://github.com/iamadamdev/bypass-paywalls-firefox
install instructions  
https://askubuntu.com/questions/37211/how-to-install-xpi-file-for-firefox

**Comment by prech** [comment]
> download ff ext https://github.com/iamadamdev/bypass-paywalls-firefox
> install instructions
> https://askubuntu.com/questions/37211/how-to-install-xpi-file-for-firefox

Thanks! No idea there's a separate version for Firefox. With Automatic Updates, too -- wonder if this feature exists in the Chrome version? or if it has to be done manually?

Washington Post does work well in Firefox

**Comment by andreaslordos** [comment]
Same issue, WaPo does not work for me either. Please fix.

**Comment by iamadamdev** [comment]
What LA times article isn't loading for you? I just loaded 10+ articles no problems. (uBlock Origin enabled)

WaPo should be fixed now for U.S. users.

**Comment by andreaslordos** [comment]
I was talking about WaPo only. This was the article I was referencing:
https://www.washingtonpost.com/opinions/the-islamic-state-might-have-found-the-perfect-propaganda-machine/2019/01/28/0d31f7ec-2036-11e9-8e21-59a09ff1e2a1_story.html

I'm in an EU country, which might be why I'm still having the issue?

**Comment by iamadamdev** [comment]
@prech We now have auto-updates on the Chrome version!
@andreaslordos WaPo not working in EU countries is a known issue, see https://github.com/iamadamdev/bypass-paywalls-chrome/issues/22

**Comment by prech** [comment]
> 

> @prech We now have auto-updates on the Chrome version!

Wonderful news, looking forward to it!

Washington Post working well in v1.4.5, thank you for being so responsive :)

**Comment by prech** [comment]
@iamadamdev Oddly, installation with the v1.4.5 CRX file wouldn't proceed. I get this below error and cannot enable the extension 
```
Bypass Paywalls
1.4.5
 This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more
ID: dcpihecpambacapedldabdbpakmachp
```

After removing, I loaded the unpacked version from the Zip and all seems fine now. Does installation from the Zip affect the auto update function?

**Comment by iamadamdev** [comment]
I put up the CRX version for Chromium users. On Chrome you are still expected to drag the whole folder over. You _should_ still get auto-updates by installing this way.

**Comment by compuguy** [comment]
The CRX version will still work if you have developer mode enabled, @iamadamdev?

**Comment by iamadamdev** [comment]
CRX is for non-Chrome Chromium-based browsers, on Chrome you should still install the extension by dragging the folder over to chrome://extensions/
