### ISSUE TITLE
inconsistency in Handelsblatt 

### ISSUE THREAD

**Issue by technoob130** [iamadamdev/bypass-paywalls-chrome#793]
sometimes i could bypass the paywall but at other times it doesn't work for the same article. i have installed ublocker and cookie remover as well. 

e.g. for this article

https://www.handelsblatt.com/finanzen/anlagestrategie/fonds-etf/vermoegensverwalter-ohne-tech-geht-nichts-auf-diese-aktien-setzen-die-erfolgreichsten-fondsmanager/25993470.html?ticket=ST-5064947-vBvjNcdbHaKBqgne2x6O-ap5

**Comment by iamadamdev** [comment]
Fixed in latest master.

**Comment by technoob130** [comment]
i still can't access the article

**Comment by iamadamdev** [comment]
Refresh, clear cookies. Then use latest master. Worked for me.

**Comment by technoob130** [comment]
removed cookies using cookie master, reinstalled from the firefox link you provided, still doesnt work

this also doesn't work
https://www.handelsblatt.com/unternehmen/management/serie-gekuendigt-was-nun-ploetzlich-perspektivlos-wie-konzerne-teure-und-erfahrene-manager-kaltstellen/26002728.html?ticket=ST-10644309-cUTW54R3nJypOYan2b7C-ap5

**Comment by iamadamdev** [comment]
I never provided a link.
It's fixed in latest master (Chrome). If you have a linux environment you can manually build a Firefox release for yourself by running the build script in `/build` otherwise you will need to wait for a Firefox release.
